version: 2

# YAML adapted from aiida-core .readthedocs.yml

# Disable all unneeded formats
formats: []

build:
  os: ubuntu-22.04
  tools:
    python: '3.11'
  jobs:
    # Use uv to speed up the build
    # https://docs.readthedocs.io/en/stable/build-customization.html#install-dependencies-with-uv
    post_create_environment:
    - asdf plugin add uv
    - asdf install uv 0.2.9
    - asdf global uv 0.2.9
    post_install:
    - VIRTUAL_ENV=$READTHEDOCS_VIRTUALENV_PATH uv pip install .[docs]

# Let the build fail if there are any warnings
sphinx:
  builder: html
  fail_on_warning: true
