name: cd

on:
    push:
        tags:
        - 'v[0-9]+.[0-9]+.[0-9]+*'

jobs:

    validate-release-tag:

        if: github.repository == 'aiidateam/aiida-hyperqueue'
        runs-on: ubuntu-latest

        steps:
        -   name: Checkout source
            uses: actions/checkout@v3

        -   name: Set up Python 3.10
            uses: actions/setup-python@v4
            with:
                python-version: '3.10'

        -   name: Validate the tag version against the package version
            run: python .github/workflows/validate_release_tag.py $GITHUB_REF

    publish:

        name: Publish to PyPI
        needs: [validate-release-tag]
        runs-on: ubuntu-latest
        environment: deployment
        permissions:
            id-token: write

        steps:
        -   name: Checkout source
            uses: actions/checkout@v3

        -   name: Set up Python 3.10
            uses: actions/setup-python@v4
            with:
                python-version: '3.10'

        -   name: Install flit
            run: pip install flit~=3.8

        -   name: Build with flit
            run: flit build

        -   name: Publish to PyPI using Trusted Publishing
            uses: pypa/gh-action-pypi-publish@release/v1
